### ISSUE TITLE
Fix iPhone width problem

### ISSUE THREAD

**Issue by ZiggyHowland** [ovevang/novocaine#3]
![12212026_10153635612820259_1849100299_n](https://cloud.githubusercontent.com/assets/15719102/11072460/3a961146-87e6-11e5-801c-a68a146ce193.jpg)

**Comment by ovevang** [comment]
Liker lysene.

**Comment by ZiggyHowland** [comment]
iPhone ok, Chrome testet og ok på laptop, men Sony Xperia Z3 viser ikke header og player tuller med plassering.

**Comment by ovevang** [comment]
Bedre nå?

**Comment by ovevang** [comment]
@media shit all over the place!
